FROM ubuntu
WORKDIR '/app'
RUN apt-get update
RUN apt-get install make
RUN apt-get -y install vim
RUN apt-get -y install gcc
RUN apt-get -y install wget
RUN apt-get -y install curl
RUN apt-get -y install strace
CMD ["/bin/bash"]